import { XOR } from "../typeUtils";

/**
 * A result from a database action.
 * `data` and `error` are mutually exclusive
 */
export type ApiRes<T> = XOR<{ data: T; }, { error: ApiError; }>

export type ApiError = {
    code: number,
    info?: string,
}

export type ApiFunction<T> = () => Promise<ApiRes<T>>;

/**
 * Parameters for creating/updating an object in the database.
 * Omits fields like IDs and timestamps that are generated by the database.
 */
export type DBObjectParams<T> = Omit<T, "id" | "createdAt" | "updatedAt" | "userId">
